logging:
  level: INFO
  loggers:
    org.village: DEBUG

# database:
#   driverClass: org.h2.Driver
#   user: sa
#   password: sa
#   url: jdbc:h2:./target/connect;MVCC=TRUE;AUTO_SERVER=TRUE

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/village-connect
  user: root
  password: mysql
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
