# logging:
#   level: INFO
#   loggers:
#     org.village: DEBUG
logging:
  level: DEBUG
  loggers:
    "io.dropwizard": INFO
    "org.eclipse": INFO
    "org.village":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./application.log
          archivedLogFilenamePattern: ./application-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console
# database:
#   driverClass: org.h2.Driver
#   user: sa
#   password: sa
#   url: jdbc:h2:./target/connect;MVCC=TRUE;AUTO_SERVER=TRUE

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/village-connect
  user: root
  password: mysql
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
